# Generated by Django 3.2.8 on 2021-10-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211028_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='media_height_inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='media_width_inches',
            field=models.IntegerField(default=0),
        ),
    ]
