# Generated by Django 3.2.8 on 2021-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('cost of goods sold', 'COGS'), ('amortization', 'AMOR'), ('selling, general, and admin', 'SG&A'), ('salary', 'SALARY'), ('rent', 'RENT')], default='selling, general, and admin', max_length=200),
        ),
    ]
